spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringDemo?user=root&password=&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Rt010610
    driver-class-name: com.mysql.cj.jdbc.Driver